# Generated by Django 3.0.4 on 2020-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfoliodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(default='null', max_length=100)),
                ('quantity', models.IntegerField(default=100)),
                ('dateofpurchase', models.DateField()),
                ('transaction', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
