# Generated by Django 3.0.4 on 2020-03-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_data_password1'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodata',
            name='tutorial_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliodata',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.user_data'),
        ),
    ]
