# Generated by Django 3.0.4 on 2020-03-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_data_password1'),
        ('portfolio', '0002_auto_20200312_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_data'),
        ),
    ]
