# Generated by Django 3.0.4 on 2020-03-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200316_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodata',
            name='current_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
