# Generated by Django 3.0.4 on 2020-03-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(default='null', max_length=100)),
                ('stockname_full', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
